### ISSUE TITLE
inactive_alpha script not working

### ISSUE THREAD

**Issue by randompersondude** [WayfireWM/pywayfire#2]
i was gonna try get all open windows with the ipc lib, so i started out with the inactive_alpha script, but i got this error:

(venv) [mark@marklaptop venv]$ python testing_ipc.py
Traceback (most recent call last):
  File "/home/mark/coding/venv/testing_ipc.py", line 8, in <module>
    sock.watch(['view-focused'])
  File "/home/mark/coding/venv/lib/python3.12/site-packages/wayfire/ipc.py", line 208, in watch
    return self.send_json(message)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mark/coding/venv/lib/python3.12/site-packages/wayfire/ipc.py", line 174, in send_json
    response = self.read_message()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/mark/coding/venv/lib/python3.12/site-packages/wayfire/ipc.py", line 64, in read_message
    raise Exception(response["error"])
Exception: No such method found!

**Comment by soreau** [comment]
Wild guess, maybe you need ipc-rules plugin enabled?

**Comment by randompersondude** [comment]
wow. it works now. sorry.
i thought it was just ipc i needed to enable?

**Comment by soreau** [comment]
Apparently not. 😁
